name: provenance-explorer
dependencies:
  - python=3.14
  - pandas
  - scipy
  - matplotlib
  - ipykernel
  - networkx
  - fastavro
  - fastparquet
  - tensorly
  - google-auth-oauthlib
  - pip
  - pip:
    - gdown
    - neo4j
    - openpyxl
    - -e .